services:
  - type: web
    name: datadash
    runtime: python
    rootDir: datadash
    buildCommand: bash build.sh
    startCommand: gunicorn datadash.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DEBUG
        value: false
