services:
  - type: web
    name: datadash
    runtime: python
    pythonVersion: 3.12
    rootDir: datadash
    buildCommand: bash build.sh
    startCommand: gunicorn datadash.wsgi:application
    envVars:
      - key: DEBUG
        value: false
